server:
  error:
    whitelabel:
      enabled: false

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: board
    password: board1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
